feature: GoodDependencies
GoodRequest/GoodIOSExtensions pull request #3
Opened 2021-08-13 09:16 UTC by andrej8888

GRSession, .swiftlint.yml, lint.swift, linted code, namedescribable without NSObject

2021-08-13 09:29 UTC, MarosNovak commented on Sources/GoodStructs/GRSession/Request+Logger.swift
> +extension URLRequest {
tu chyba prazdny riadok

2021-08-13 09:29 UTC, MarosNovak commented on Sources/GoodStructs/GRSession/Request+Logger.swift
> +        return DataResponse<T, AFError>(request: request, response: response, data: data, metrics: .none, serializationDuration: 30, result: AFResult<T>.success(value))
toto by som zalomil na 2 riadky

2021-08-13 09:29 UTC, MarosNovak commented on Sources/GoodStructs/GRSession/Request+Extensions.swift
> +    func goodify<T: Decodable>(type: T.Type = T.self,
takto uz zalamovanie nepiseme

2021-08-13 09:29 UTC, MarosNovak commented on Sources/GoodStructs/GRSession/Request+Extensions.swift
> +    func goodify<T: Decodable>(type: T.Type = T.self,
v celom subore

2021-08-13 11:36 UTC, valeriiklmnko commented on Sources/GoodStructs/GRSession/GRSession.swift
> +        default: break
Uz nepiseme na jeden riadok break musi byt na novom

2021-08-13 11:37 UTC, valeriiklmnko commented on Sources/GoodStructs/GRSession/GRSession.swift
> +        default: break
break na novom

2021-08-13 11:37 UTC, valeriiklmnko commented on Sources/GoodStructs/GRSession/GRSession.swift
> +            urlComponent?.queryItems = params.map {
Je iba jeden operator map mozme dat na 1 riadok

2021-08-13 11:39 UTC, valeriiklmnko commented
Vela kde mame 1 line computed property kde je napisany return nestalo by za to pridat na ten return pravidlo/autocorrect?

2021-08-16 07:32 UTC, smajdalf requested changes
Request manager odtialto mozes zatial dat prec. Mam to u seba pripravene a troska upravene, lebo je tam potrebne viac tyzch veci dat public etc. 

Zaroven to bude ako samostatny modul vramci GoodExtensions. Do GoodStructs by som toto az tak moc nedaval, nech to mame pekne oddelene.

2021-09-09 08:31 UTC, smajdalf commented
@andrej8888 mozes odstranit ten request manager ktory tam pridam ako samostatny modul?

2021-09-09 12:56 UTC, smajdalf commented
@andrej8888  pls rebase a spusti swiftlint :) nasledne to mergneme.

2021-09-09 15:49 UTC, closed without merging